global:
  clusterDomain: cluster.local
  identityTrustAnchorsPEM: |
    <path:kv/data/linkerd-prod/root-ca#pem>

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls

proxy:
  logLevel: warn,linkerd=info
  resources:
    requests: { cpu: 200m, memory: 192Mi }
    limits:   { cpu: 400m, memory: 256Mi }

controllerReplicas: 3
proxyInjector:
  replicas: 3
policyController:
  enabled: true
