trustAnchor: |
  -----BEGIN CERTIFICATE-----
  STAGE_TRUST_CA
  -----END CERTIFICATE-----

issuer:
  crt: |
    -----BEGIN CERTIFICATE-----
    STAGE_ISSUER_CERT
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    STAGE_ISSUER_KEY
    -----END PRIVATE KEY-----
