# Production environment values for Linkerd
identity:
  issuer:
    scheme: kubernetes.io/tls
    crtPEM: "{{ vault 'linkerd/prod' 'issuer_crt' }}"
    keyPEM: "{{ vault 'linkerd/prod' 'issuer_key' }}"
    caPEM: "{{ vault 'linkerd/prod' 'ca_crt' }}"

controllerReplicas: 3
enablePodAntiAffinity: true
proxy:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi
