installNamespace: true
controllerReplicas: 3
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: linkerd.io/tls
    crtPEMFile: /home/nolet7/linkerd-certs/issuer.crt
    keyPEMFile: /home/nolet7/linkerd-certs/issuer.key
    crtExpiry: 720h
  trustAnchorsFile: /home/nolet7/linkerd-certs/ca.crt

global:
  linkerdVersion: stable-2.13.3
  identity:
    issuer:
      crtExpiry: 720h
      renewBeforeExpiry: 168h
  proxy:
    logLevel: warn,linkerd=info

resources:
  requests:
    cpu: 500m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi
