# Development environment values for Linkerd
identity:
  issuer:
    scheme: kubernetes.io/tls
    crtPEM: "{{ vault 'linkerd/dev' 'issuer_crt' }}"
    keyPEM: "{{ vault 'linkerd/dev' 'issuer_key' }}"
    caPEM: "{{ vault 'linkerd/dev' 'ca_crt' }}"

controllerReplicas: 1
enablePodAntiAffinity: false
proxy:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 128Mi
