# helm/values/values-stage.yaml
installNamespace: true

controllerReplicas: 2
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: linkerd.io/tls
    crtPEM: |
      -----BEGIN CERTIFICATE-----
      # staging issuer cert
      -----END CERTIFICATE-----
    keyPEM: |
      -----BEGIN RSA PRIVATE KEY-----
      # staging issuer key
      -----END RSA PRIVATE KEY-----
  trustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    # staging trust anchor
    -----END CERTIFICATE-----

proxy:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
  logLevel: debug
  trace:
    collector:
      enabled: true
      addr: opentelemetry-collector.monitoring:4317

global:
  linkerdVersion: stable-2.13.3
  proxy:
    logLevel: info,linkerd=debug

metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 4191

nodeSelector:
  environment: stage

