installNamespace: true
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: kubernetes.io/tls

proxyInjector:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

controllerReplicas: 2
