# ==========================================================
# LINKERD PRODUCTION VALUES
# ==========================================================

global:
  clusterDomain: cluster.local
  proxy:
    logLevel: warn,linkerd=info
  identityTrustAnchorsPEM: |
    {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.trust_anchor_crt }}{{- end }}

identity:
  issuer:
    scheme: kubernetes.io/tls
    crtPEM: |
      {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.issuer_crt }}{{- end }}
    keyPEM: |
      {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.issuer_key }}{{- end }}

# ----------------------------------------------------------
# Proxy Configuration
# ----------------------------------------------------------
proxy:
  image:
    name: cr.l5d.io/linkerd/proxy
    version: stable-2.14.10
  logLevel: warn,linkerd=info
  resources:
    requests:
      cpu: 200m
      memory: 192Mi
    limits:
      cpu: 400m
      memory: 256Mi

# ----------------------------------------------------------
# Controller Plane Configuration
# ----------------------------------------------------------
controllerReplicas: 3
controllerResources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

# ----------------------------------------------------------
# Destination & Identity Services
# ----------------------------------------------------------
destinationControllerResources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

identityResources:
  requests:
    cpu: 150m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

# ----------------------------------------------------------
# Proxy Injector & Policy Controller
# ----------------------------------------------------------
proxyInjector:
  replicas: 3
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 400Mi

policyController:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ----------------------------------------------------------
# Telemetry & Metrics (integrated with Linkerd Viz)
# ----------------------------------------------------------
metrics:
  enabled: true
  scrapeInterval: 10s
  retentionTime: 12h

# ----------------------------------------------------------
# Viz Addons (HA)
# ----------------------------------------------------------
grafana:
  enabled: true
  replicas: 2
  persistence:
    enabled: true
    size: 10Gi
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi

prometheus:
  enabled: true
  retention: 24h
  scrapeInterval: 10s
  resources:
    requests:
      cpu: 300m
      memory: 256Mi
    limits:
      cpu: 800m
      memory: 512Mi

tap:
  enabled: true
tapInjector:
  enabled: true

# ----------------------------------------------------------
# HA / Node Affinity
# ----------------------------------------------------------
highAvailability:
  enabled: true
  replicas: 3
  antiAffinity: hard

# ----------------------------------------------------------
# Tracing (optional)
# ----------------------------------------------------------
tracing:
  enabled: false
