installNamespace: true
controllerReplicas: 2
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: linkerd.io/tls
    crtPEMFile: /home/nolet7/linkerd-certs/issuer.crt
    keyPEMFile: /home/nolet7/linkerd-certs/issuer.key
    crtExpiry: 336h
  trustAnchorsFile: /home/nolet7/linkerd-certs/ca.crt

global:
  linkerdVersion: stable-2.13.3
  identity:
    issuer:
      crtExpiry: 336h
      renewBeforeExpiry: 72h
  proxy:
    logLevel: info,linkerd=debug

resources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi
