# Staging environment values for Linkerd
identity:
  issuer:
    scheme: kubernetes.io/tls
    crtPEM: "{{ vault 'linkerd/stage' 'issuer_crt' }}"
    keyPEM: "{{ vault 'linkerd/stage' 'issuer_key' }}"
    caPEM: "{{ vault 'linkerd/stage' 'ca_crt' }}"

controllerReplicas: 2
enablePodAntiAffinity: true
proxy:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi
