installNamespace: true
enablePodAntiAffinity: false

identity:
  issuer:
    scheme: kubernetes.io/tls

proxyInjector:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

controllerReplicas: 1
