# Linkerd Helm values for PROD environment
namespace: linkerd-prod

identity:
  issuer:
    scheme: kubernetes.io/tls
  externalCA: true
  existingIssuerSecret: linkerd-identity-issuer

controllerReplicas: 3

resources:
  requests:
    cpu: 500m
    memory: 1Gi
  limits:
    cpu: 1
    memory: 2Gi

proxy:
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 400m
      memory: 512Mi

enablePodInject: true

nodeSelector:
  env: prod

metrics:
  enableGrafana: true
  enablePrometheus: true
  enableJaeger: true

