# helm/values/values-prod.yaml
installNamespace: true

controllerReplicas: 3
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: linkerd.io/tls
    crtPEM: |
      -----BEGIN CERTIFICATE-----
      # production issuer certificate
      -----END CERTIFICATE-----
    keyPEM: |
      -----BEGIN RSA PRIVATE KEY-----
      # production issuer private key
      -----END RSA PRIVATE KEY-----
  trustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    # production trust anchor
    -----END CERTIFICATE-----

proxy:
  resources:
    requests:
      cpu: 150m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  logLevel: info
  trace:
    collector:
      enabled: true
      addr: otel-collector.monitoring:4317

global:
  linkerdVersion: stable-2.13.3
  proxy:
    logLevel: warn,linkerd=info
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    # (optional additional root)
    -----END CERTIFICATE-----

metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 4191

tolerations:
  - key: "critical-service"
    operator: "Exists"
    effect: "NoSchedule"

affinity:
  podAntiAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
            - key: app
              operator: In
              values: ["linkerd-controller"]
        topologyKey: kubernetes.io/hostname

