trustAnchor: |
  -----BEGIN CERTIFICATE-----
  DEV_TRUST_CA
  -----END CERTIFICATE-----

issuer:
  crt: |
    -----BEGIN CERTIFICATE-----
    DEV_ISSUER_CERT
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    DEV_ISSUER_KEY
    -----END PRIVATE KEY-----
