# ==========================================================
# LINKERD STAGE VALUES
# ==========================================================

global:
  clusterDomain: cluster.local
  proxy:
    logLevel: info
    resources:
      requests:
        cpu: 150m
        memory: 192Mi
      limits:
        cpu: 400m
        memory: 384Mi

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    certFile: /vault/secrets/issuer.crt
    keyFile: /vault/secrets/issuer.key

vault:
  enabled: true
  address: "http://48.217.51.59:8200"
  role: "linkerd-stage"
  authPath: "auth/kubernetes"
  pkiPath: "pki_int/issue/linkerd-stage"
  mountPath: "/vault/secrets"

controllerReplicas: 2

metrics:
  enabled: true
  scrapeInterval: 15s
  retentionTime: 6h

proxyInjector:
  replicas: 2
  resources:
    requests:
      cpu: 150m
      memory: 128Mi
    limits:
      cpu: 400m
      memory: 256Mi

policyController:
  enabled: true

grafana:
  enabled: true

prometheus:
  enabled: true
