# helm/values/values-dev.yaml
installNamespace: true

controllerReplicas: 1
enablePodAntiAffinity: false

identity:
  issuer:
    scheme: linkerd.io/tls
    crtPEM: |
      -----BEGIN CERTIFICATE-----
      # (Optional: test cluster CA cert)
      -----END CERTIFICATE-----
    keyPEM: |
      -----BEGIN RSA PRIVATE KEY-----
      # (Optional: test cluster key)
      -----END RSA PRIVATE KEY-----
  trustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    # (Optional: root trust anchor)
    -----END CERTIFICATE-----

proxy:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  logLevel: info
  trace:
    collector:
      enabled: false

global:
  linkerdVersion: stable-2.13.3
  proxy:
    logLevel: warn,linkerd=info

metrics:
  enabled: true
  prometheus:
    enabled: true
    port: 4191

