# ==========================================================
# LINKERD DEV VALUES
# ==========================================================

global:
  clusterDomain: cluster.local
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls
    certFile: /vault/secrets/issuer.crt
    keyFile: /vault/secrets/issuer.key

vault:
  enabled: true
  address: "http://48.217.51.59:8200"
  role: "linkerd"
  authPath: "auth/kubernetes"
  pkiPath: "pki_int/issue/linkerd"
  mountPath: "/vault/secrets"

controllerReplicas: 1

metrics:
  enabled: true
  scrapeInterval: 10s
  retentionTime: 1h

proxyInjector:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 200Mi

policyController:
  enabled: true

grafana:
  enabled: true

prometheus:
  enabled: true
