# Linkerd Helm values for STAGE environment
namespace: linkerd-stage

identity:
  issuer:
    scheme: kubernetes.io/tls
  externalCA: true
  existingIssuerSecret: linkerd-identity-issuer

controllerReplicas: 2

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 400m
    memory: 1Gi

proxy:
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi

enablePodInject: true

nodeSelector:
  env: stage

metrics:
  enableGrafana: true
  enablePrometheus: true
  enableJaeger: false

