# Linkerd Helm values for DEV environment
namespace: linkerd-dev

identity:
  issuer:
    scheme: kubernetes.io/tls
  externalCA: true
  existingIssuerSecret: linkerd-identity-issuer

controllerReplicas: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 200m
    memory: 512Mi

proxy:
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi

# Enable automatic mTLS for all injected workloads
enablePodInject: true

# Add environment labels
nodeSelector:
  env: dev

# Optional telemetry tweaks
metrics:
  enableGrafana: true
  enablePrometheus: true
  enableJaeger: false

