# ==========================================================
# LINKERD DEV VALUES
# ==========================================================

global:
  clusterDomain: cluster.local
  proxy:
    logLevel: debug
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 300m
        memory: 256Mi
  identityTrustAnchorsPEM: |
    {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.trust_anchor_crt }}{{- end }}

identity:
  issuer:
    scheme: kubernetes.io/tls
    crtPEM: |
      {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.issuer_crt }}{{- end }}
    keyPEM: |
      {{- with secret "secret/platform-tools/linkerd" -}}{{ .Data.data.issuer_key }}{{- end }}

# ----------------------------------------------------------
# Proxy Configuration
# ----------------------------------------------------------
proxy:
  image:
    name: cr.l5d.io/linkerd/proxy
    version: stable-2.14.10
  logLevel: debug,linkerd=info
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 300m
      memory: 256Mi

# ----------------------------------------------------------
# Controller Plane Configuration
# ----------------------------------------------------------
controllerReplicas: 1
controllerResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 400m
    memory: 512Mi

# ----------------------------------------------------------
# Destination & Identity Services
# ----------------------------------------------------------
destinationControllerResources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 400m
    memory: 256Mi

identityResources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

# ----------------------------------------------------------
# Proxy Injector & Policy Controller
# ----------------------------------------------------------
proxyInjector:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 300m
      memory: 200Mi

policyController:
  enabled: true

# ----------------------------------------------------------
# Telemetry
# ----------------------------------------------------------
metrics:
  enabled: true
  scrapeInterval: 10s
  retentionTime: 1h

# ----------------------------------------------------------
# Viz Addons
# ----------------------------------------------------------
grafana:
  enabled: true
prometheus:
  enabled: true
tap:
  enabled: true
tapInjector:
  enabled: true
