installNamespace: true
enablePodAntiAffinity: true

identity:
  issuer:
    scheme: kubernetes.io/tls

proxyInjector:
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

controllerReplicas: 3
highAvailability: true
