global:
  clusterDomain: cluster.local
  identityTrustAnchorsPEM: |
    <path:kv/data/linkerd/root-ca#pem>   # AVP injects Root CA PEM at render-time

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls            # chart reads Secret linkerd-identity-issuer

proxy:
  logLevel: debug,linkerd=info
  resources:
    requests: { cpu: 100m, memory: 128Mi }
    limits:   { cpu: 300m, memory: 256Mi }

controllerReplicas: 1
proxyInjector:
  replicas: 1
policyController:
  enabled: true
