global:
  clusterDomain: cluster.local
  identityTrustAnchorsPEM: |
    <path:kv/data/linkerd-stage/root-ca#pem>

identity:
  externalCA: true
  issuer:
    scheme: kubernetes.io/tls

proxy:
  logLevel: info,linkerd=info
  resources:
    requests: { cpu: 150m, memory: 192Mi }
    limits:   { cpu: 400m, memory: 384Mi }

controllerReplicas: 2
proxyInjector:
  replicas: 2
policyController:
  enabled: true
