trustAnchor: |
  -----BEGIN CERTIFICATE-----
  PROD_TRUST_CA
  -----END CERTIFICATE-----

issuer:
  crt: |
    -----BEGIN CERTIFICATE-----
    PROD_ISSUER_CERT
    -----END CERTIFICATE-----
  key: |
    -----BEGIN PRIVATE KEY-----
    PROD_ISSUER_KEY
    -----END PRIVATE KEY-----
