# ==========================================================
# Linkerd Control Plane Helm Values - Production Environment
# Managed via Argo CD + Kustomize
# ==========================================================

installNamespace: false
enablePodAntiAffinity: true
enableEndpointSlices: true
autoInject: true

# ------------------------- Identity -----------------------
identityTrustAnchorsPEM: ""
identity:
  issuer:
    scheme: kubernetes.io/tls
  clockSkewAllowance: "30s"
  issuerLifetime: "72h"
  certManager: false

# -------------------------- Proxy -------------------------
proxy:
  image:
    name: cr.l5d.io/linkerd/proxy
    version: stable-2.14.10
  logLevel: warn,linkerd=info
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  livenessProbe:
    periodSeconds: 10
  readinessProbe:
    periodSeconds: 5

# ----------------------- Controllers -----------------------
controllerReplicas: 3
controllerResources:
  requests:
    cpu: 300m
    memory: 400Mi
  limits:
    cpu: 1
    memory: 1Gi

destinationControllerResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

identityResources:
  requests:
    cpu: 200m
    memory: 256Mi
  limits:
    cpu: 600m
    memory: 512Mi

proxyInjector:
  replicas: 2
  resources:
    requests:
      cpu: 200m
      memory: 200Mi
    limits:
      cpu: 500m
      memory: 400Mi

policyController:
  enabled: true
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi

tap:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 256Mi
    limits:
      cpu: 600m
      memory: 512Mi

# ---------------------- Telemetry --------------------------
metrics:
  enabled: true
  scrapeInterval: 5s
  retentionTime: 12h

grafana:
  enabled: true
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 600m
      memory: 1Gi

prometheus:
  enabled: true
  retention: 24h
  scrapeInterval: 5s
  resources:
    requests:
      cpu: 400m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi

# -------------------- High Availability -------------------
highAvailability:
  enabled: true
  replicas: 3
  antiAffinity: hard

# ------------------------- Global -------------------------
global:
  clusterDomain: cluster.local
  proxy:
    resources:
      requests:
        cpu: 300m
        memory: 512Mi
      limits:
        cpu: 1
        memory: 1Gi
